# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Objekt_status_GDB_dialog_base.ui'
#
# Created: Wed Aug 02 15:00:03 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Objekt_status_GDBDialogBase(object):
    def setupUi(self, Objekt_status_GDBDialogBase):
        Objekt_status_GDBDialogBase.setObjectName(_fromUtf8("Objekt_status_GDBDialogBase"))
        Objekt_status_GDBDialogBase.resize(481, 563)
        self.tabWidget = QtGui.QTabWidget(Objekt_status_GDBDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 461, 531))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 300, 404, 201))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_1 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.gridLayout.addWidget(self.checkBox_1, 0, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout.addWidget(self.checkBox_5, 0, 1, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout.addWidget(self.checkBox_9, 0, 2, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout.addWidget(self.checkBox_6, 1, 1, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout.addWidget(self.checkBox_10, 1, 2, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout.addWidget(self.checkBox_7, 2, 1, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout.addWidget(self.checkBox_11, 2, 2, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout.addWidget(self.checkBox_8, 3, 1, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout.addWidget(self.checkBox_12, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(60, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_Save_dir = QtGui.QLineEdit(self.tab)
        self.lineEdit_Save_dir.setGeometry(QtCore.QRect(150, 170, 261, 20))
        self.lineEdit_Save_dir.setObjectName(_fromUtf8("lineEdit_Save_dir"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton_Save_dir = QtGui.QPushButton(self.tab)
        self.pushButton_Save_dir.setGeometry(QtCore.QRect(420, 170, 31, 23))
        self.pushButton_Save_dir.setObjectName(_fromUtf8("pushButton_Save_dir"))
        self.comboBox_geom_status = QtGui.QComboBox(self.tab)
        self.comboBox_geom_status.setGeometry(QtCore.QRect(220, 110, 231, 22))
        self.comboBox_geom_status.setObjectName(_fromUtf8("comboBox_geom_status"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_run = QtGui.QPushButton(self.tab)
        self.pushButton_run.setGeometry(QtCore.QRect(164, 220, 81, 23))
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.comboBox_obj_status = QtGui.QComboBox(self.tab)
        self.comboBox_obj_status.setGeometry(QtCore.QRect(220, 60, 231, 22))
        self.comboBox_obj_status.setObjectName(_fromUtf8("comboBox_obj_status"))
        self.comboBox_kommune = QtGui.QComboBox(self.tab)
        self.comboBox_kommune.setGeometry(QtCore.QRect(220, 10, 231, 22))
        self.comboBox_kommune.setObjectName(_fromUtf8("comboBox_kommune"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(105, 260, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBoxCredentials = QtGui.QGroupBox(self.tab_2)
        self.groupBoxCredentials.setGeometry(QtCore.QRect(10, 20, 391, 181))
        self.groupBoxCredentials.setObjectName(_fromUtf8("groupBoxCredentials"))
        self.db_name = QtGui.QLineEdit(self.groupBoxCredentials)
        self.db_name.setGeometry(QtCore.QRect(100, 30, 261, 20))
        self.db_name.setObjectName(_fromUtf8("db_name"))
        self.label_5 = QtGui.QLabel(self.groupBoxCredentials)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.db_host = QtGui.QLineEdit(self.groupBoxCredentials)
        self.db_host.setGeometry(QtCore.QRect(100, 60, 261, 20))
        self.db_host.setObjectName(_fromUtf8("db_host"))
        self.label_6 = QtGui.QLabel(self.groupBoxCredentials)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.db_user = QtGui.QLineEdit(self.groupBoxCredentials)
        self.db_user.setGeometry(QtCore.QRect(100, 90, 261, 20))
        self.db_user.setObjectName(_fromUtf8("db_user"))
        self.label_7 = QtGui.QLabel(self.groupBoxCredentials)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.db_password = QtGui.QLineEdit(self.groupBoxCredentials)
        self.db_password.setGeometry(QtCore.QRect(100, 120, 261, 20))
        self.db_password.setObjectName(_fromUtf8("db_password"))
        self.label_8 = QtGui.QLabel(self.groupBoxCredentials)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.db_port = QtGui.QLineEdit(self.groupBoxCredentials)
        self.db_port.setGeometry(QtCore.QRect(100, 150, 261, 20))
        self.db_port.setObjectName(_fromUtf8("db_port"))
        self.label_9 = QtGui.QLabel(self.groupBoxCredentials)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.button_box = QtGui.QDialogButtonBox(Objekt_status_GDBDialogBase)
        self.button_box.setGeometry(QtCore.QRect(110, 840, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))

        self.retranslateUi(Objekt_status_GDBDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), Objekt_status_GDBDialogBase.reject)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), Objekt_status_GDBDialogBase.accept)
        QtCore.QMetaObject.connectSlotsByName(Objekt_status_GDBDialogBase)

    def retranslateUi(self, Objekt_status_GDBDialogBase):
        Objekt_status_GDBDialogBase.setWindowTitle(_translate("Objekt_status_GDBDialogBase", "Objekt_status_GDB", None))
        self.label_2.setText(_translate("Objekt_status_GDBDialogBase", "Vælg Objekt Status:", None))
        self.checkBox_1.setText(_translate("Objekt_status_GDBDialogBase", "Bygning", None))
        self.checkBox_5.setText(_translate("Objekt_status_GDBDialogBase", "Jernbanebrudt", None))
        self.checkBox_9.setText(_translate("Objekt_status_GDBDialogBase", "Vandloebsmidtebrudt", None))
        self.checkBox_2.setText(_translate("Objekt_status_GDBDialogBase", "Bygvaerk", None))
        self.checkBox_6.setText(_translate("Objekt_status_GDBDialogBase", "Soe", None))
        self.checkBox_10.setText(_translate("Objekt_status_GDBDialogBase", "Vejkant", None))
        self.checkBox_3.setText(_translate("Objekt_status_GDBDialogBase", "Badebaadebro", None))
        self.checkBox_7.setText(_translate("Objekt_status_GDBDialogBase", "Tekniskareal", None))
        self.checkBox_11.setText(_translate("Objekt_status_GDBDialogBase", "Vejmidtebrudt", None))
        self.checkBox_4.setText(_translate("Objekt_status_GDBDialogBase", "Havn", None))
        self.checkBox_8.setText(_translate("Objekt_status_GDBDialogBase", "Telemast", None))
        self.checkBox_12.setText(_translate("Objekt_status_GDBDialogBase", "Vindmoelle", None))
        self.label.setText(_translate("Objekt_status_GDBDialogBase", "Vælg Kommune:", None))
        self.label_3.setText(_translate("Objekt_status_GDBDialogBase", "Gem resultat :", None))
        self.pushButton_Save_dir.setText(_translate("Objekt_status_GDBDialogBase", "...", None))
        self.label_4.setText(_translate("Objekt_status_GDBDialogBase", "Vælg Geometri Status:", None))
        self.pushButton_run.setText(_translate("Objekt_status_GDBDialogBase", "Søg", None))
        self.label_10.setText(_translate("Objekt_status_GDBDialogBase", "Søgbare Objekter:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Objekt_status_GDBDialogBase", "Tab 1", None))
        self.groupBoxCredentials.setTitle(_translate("Objekt_status_GDBDialogBase", "Database credentials", None))
        self.label_5.setText(_translate("Objekt_status_GDBDialogBase", "Database", None))
        self.label_6.setText(_translate("Objekt_status_GDBDialogBase", "Hostname", None))
        self.label_7.setText(_translate("Objekt_status_GDBDialogBase", "Username", None))
        self.label_8.setText(_translate("Objekt_status_GDBDialogBase", "Password", None))
        self.label_9.setText(_translate("Objekt_status_GDBDialogBase", "Port", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Objekt_status_GDBDialogBase", "Tab 2", None))

